fix(ecr validate login)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -79,12 +79,18 @@ jobs:
           echo "Docker Username: AWS"
           echo "Docker Password: $(aws ecr get-login-password --region ap-southeast-1 | head -c 8)******"  # Mask most of the password for security
           aws ecr get-login-password --region ap-southeast-1 > /dev/null || echo "Failed to fetch ECR password"
-          
+
       - name: Login to ECR
         run: |
           echo "Attempting to log in to ECR"
-          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 637423177853.dkr.ecr.ap-southeast-1.amazonaws.com || exit 1
-          echo "Login to ECR succeeded!"
+          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 637423177853.dkr.ecr.ap-southeast-1.amazonaws.com
+          if [ $? -eq 0 ]; then
+            echo "Login to ECR succeeded!"
+          else
+            echo "Login to ECR failed!" >&2
+            exit 1
+          fi
+
 
       - name: Build, push docker image
         env:
